@RedisExample_HostAddress = http://localhost:5204

GET {{RedisExample_HostAddress}}/api/redis-stream-publisher
Accept: application/json
###
GET {{RedisExample_HostAddress}}/api/api/redis-stream-publisher-error
Accept: application/json
