@RedisExample_HostAddress = http://localhost:5204

GET {{RedisExample_HostAddress}}/api/redis-stream-publisher
Accept: application/json
###
GET {{RedisExample_HostAddress}}/api/redis-stream-publisher-error
Accept: application/json
###
GET {{RedisExample_HostAddress}}/api/pubsub/publish
Accept: application/json
###
POST {{RedisExample_HostAddress}}/api/events/order/create
Accept: application/json
###
POST {{RedisExample_HostAddress}}/api/events/payment/process
Accept: application/json




